#配置datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  #配置jsp映射
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#配置端口和contextPath
server:
  port: 8888
  servlet:
    context-path: /smbms

#配置thymeleaf映射
#配置freeworker映射

#配置拦截器。。。

